### ISSUE TITLE
createifnotfound adds new users to groups, but does not add existing users to groups

### ISSUE THREAD

**Issue by victorhooi** [taers232c/GAMADV-XTD3#35]
I'm using the following command to add users to groups:

```
~/bin/gamadv-xtd3/gam csv Users.csv gam update user ~email firstname ~firstname lastname ~lastname ou ~ou createifnotfound notify ~altemail password random groups ~group
Using 2 processes...
User: test3@example.org, Updated
User: test4@example.org, Created
User: test4@example.org, Add to 1 Group
Recipient: victorhooi@yahoo.com, Message: Account test3@example.org password has been changed, Email Sent
  Group: vendors@example.org, Member: test4@example.org, Added
```

In this case, test3@example.org is an existing user, test4@example.org is a new user being created.

test3@example.org was *not* added to the group in the CSV file, but test4 was created with the group in the CSV file.

Is it expected behaviour that groups are set for new users, but not updated for existing users?

**Comment by taers232c** [comment]
Victor,

This is the expected behavior; the question is whether it is the desired behavior?
When a user is created, it can't already belong to any groups so adding it to groups ~group will cause no problems.
When a user is updated, it may already belong to some groups which would cause duplicate errors if groups ~group contains those groups.
Should the user be deleted from any groups not specified in groups ~group?

Ross
--
ross.scroggs@gmail.com
