### ISSUE TITLE
Print ACLS for New Gsites

### ISSUE THREAD

**Issue by dav1303** [taers232c/GAMADV-XTD3#39]
Hi

When I launch a print command on a file which is a Gsite on My Drive it shows me only :

- owners
- writers
- domain

Readers are not print to my file !

Thanks

**Comment by taers232c** [comment]
I see the same behavior, the API isn't returning the readers.

Go here: https://developers.google.com/drive/api/v3/reference/permissions/list

* Login in as the user that owns the site file.
* Put the site file ID in the fileId field
* Click Execute
* Verify that there are no readers
* Call Google and let them know what you see/what you want.

By using this site, it keeps GAM out of the discussion with Google, they can't avoid helping because you're using third-party software.

Ross

**Comment by dav1303** [comment]
Hi

I have open an issue

Thanks
