### ISSUE TITLE
Total Licenses count

### ISSUE THREAD

**Issue by grubjack** [taers232c/GAMADV-XTD3#61]
Hi,

There is some way to get the total amount of Gsuite licenses?

Trying

`gam info customer`
...
`WARNING: No User counts data available.`

--
GAMADV-X 4.90.00 - https://github.com/taers232c/GAMADV-X
Ross Scroggs <ross.scroggs@gmail.com>
Python 2.7.13 64-bit final
google-api-python-client 1.7.8
httplib2 0.13.0
oauth2client 4.1.3

**Comment by taers232c** [comment]
Updated code in `gam info domain` to perform retries when getting license information to
avoid this warning: `WARNING: No User counts data available.`

This is fixed in 5.03.28.

You are on an unsupported version of GAMADV-X, see the following to upgrade to the latest supported version.

https://github.com/taers232c/GAMADV-XTD3/wiki/How-to-Upgrade-from-GAMADV-X-or-GAMADV-XTD
